version: '3.7'

networks:
  coganet:

services:
  api-mocks:
    image: rodolpheche/wiremock
    volumes:
      - "./api-mocks:/home/wiremock"
    ports:
      - "8080:8080"
    networks:
      - coganet
    command: ["--verbose", "--no-request-journal"]

  cogboard:
    image: cogboard/cogboard-app
    volumes:
      - "./mnt:/data"
    networks:
      - coganet
    ports:
      - "8092:8092"
      - "9001:9001"
